### ISSUE TITLE
support custom HTTP headers on requests

### ISSUE THREAD

**Issue by mikewyszinski** [cosmos-client/cosmos-client-ts#105]
we have a need to support custom HTTP headers on requests to our endpoints (to control traffic). It does not look like we are able to do that with this library.  can you confirm this is the case? and if so, would it be possible for you to make a change to support this?

**Comment by KimuraYu45z** [comment]
Consider to edit `config.Axios` object.

https://github.com/cosmos-client/cosmos-client-ts/blob/main/src/config/module.ts#L1
https://github.com/cosmos-client/cosmos-client-ts/blob/main/src/rest/config.ts#L3

**Comment by mikewyszinski** [comment]
Hi! thanks for the reply!

that would add headers to every axios  request regardless of destination (and we use axios to call many different blockchain endpoints), that may cause other  issues.  

is it at all feasible to make a change to expose the Configuration that comes with the  auto-generated code?

it seems currently it's always undefined see --> https://github.com/cosmos-client/cosmos-client-ts/blob/main/src/rest/bank/module.ts#L23
