### ISSUE TITLE
Is `sr25519` library still required?

### ISSUE THREAD

**Issue by JonnyBurger** [cosmos-client/cosmos-client-ts#29]
We are trying to run this library in React Native and struggle because of the `sr25519` library.

We see that it's in the package.json but not imported anywhyere. Can we send a pull request to remove it? Or is it needed in way still?

**Comment by KimuraYu45z** [comment]
I'm sorry for confusing specification.

You may be able to avoid some error by customizing configurations of bundler like webpack.

e.g. `webpack.config.js`

```js
module.exports = {
  resolve: {
    extensions: ['.wasm'],
  },
};
```

This may help you but if you are still struggle though did it, plz create a pull request to remove `sr25519`.
Thanks.

**Comment by KimuraYu45z** [comment]
Thanks. I'll publish as a version `v0.42.5` soon. Just a moment.

**Comment by KimuraYu45z** [comment]
https://github.com/cosmos-client/cosmos-client-ts/releases/tag/v0.42.5
I just created a release. GitHub Actions workflow will publish it. Thanks.

**Comment by JonnyBurger** [comment]
Thanks for the super swift action! 🙌

**Comment by KimuraYu45z** [comment]
https://github.com/cosmos-client/cosmos-client-ts/runs/2793370637
deployment completed. Thanks for your cooperation.
