### ISSUE TITLE
Where is openapi.yaml source file ?

### ISSUE THREAD

**Issue by typhoonbb** [cosmos-client/cosmos-client-ts#50]
Can any one tell me where is `openapi.yaml` source file ? In case I want to modify it to re-generate `src` folder's code,  Thank you very much

**Comment by KimuraYu45z** [comment]
Hi

https://github.com/cosmos-client/cosmos-client-ts/blob/main/gen-openapi.sh#L4

We are using the swagger.yaml existing in cosmos-sdk repository.

**Comment by typhoonbb** [comment]
> Hi
> 
> https://github.com/cosmos-client/cosmos-client-ts/blob/main/gen-openapi.sh#L4
> 
> We are using the swagger.yaml existing in cosmos-sdk repository.

Thanks a lot
